/*
 * Copyright (c) 2025 SAP SE or an SAP affiliate company. All rights reserved.
 *
 * This is a generated file powered by the SAP Cloud SDK for JavaScript.
 */
import {
  Entity,
  DefaultDeSerializers,
  DeSerializers,
  DeserializedType
} from '@sap-cloud-sdk/odata-v4';
import type { BlwiApi } from './BlwiApi';
import { TradeBlwiCustVend } from './TradeBlwiCustVend';
import { NoYes } from './NoYes';

/**
 * This class represents the entity "BLWI" of service "d365_metadata".
 */
export class Blwi<T extends DeSerializers = DefaultDeSerializers>
  extends Entity
  implements BlwiType<T>
{
  /**
   * Technical entity name for Blwi.
   */
  static override _entityName = 'BLWI';
  /**
   * Default url path for the according service.
   */
  static override _defaultBasePath = '/';
  /**
   * All key fields of the Blwi entity.
   */
  static _keys = [
    'dataAreaId',
    'Company',
    'BLWITransaction',
    'AccountNumber',
    'Voucher',
    'Invoice',
    'TransactionDate'
  ];
  /**
   * Data Area Id.
   */
  declare dataAreaId: DeserializedType<T, 'Edm.String'>;
  /**
   * Company.
   */
  declare company: DeserializedType<T, 'Edm.String'>;
  /**
   * Blwi Transaction.
   * @nullable
   */
  declare blwiTransaction?: TradeBlwiCustVend | null;
  /**
   * Account Number.
   */
  declare accountNumber: DeserializedType<T, 'Edm.String'>;
  /**
   * Voucher.
   */
  declare voucher: DeserializedType<T, 'Edm.String'>;
  /**
   * Invoice.
   */
  declare invoice: DeserializedType<T, 'Edm.String'>;
  /**
   * Transaction Date.
   */
  declare transactionDate: DeserializedType<T, 'Edm.DateTimeOffset'>;
  /**
   * Amount In Transaction Currency.
   */
  declare amountInTransactionCurrency: DeserializedType<T, 'Edm.Decimal'>;
  /**
   * Reporting Date.
   */
  declare reportingDate: DeserializedType<T, 'Edm.DateTimeOffset'>;
  /**
   * Auto Generated.
   * @nullable
   */
  declare autoGenerated?: NoYes | null;
  /**
   * Country Region Group Row Number.
   */
  declare countryRegionGroupRowNumber: DeserializedType<T, 'Edm.Int32'>;
  /**
   * Currency.
   * @nullable
   */
  declare currency?: DeserializedType<T, 'Edm.String'> | null;
  /**
   * Country Region Group Id.
   * @nullable
   */
  declare countryRegionGroupId?: DeserializedType<T, 'Edm.String'> | null;
  /**
   * Included.
   * @nullable
   */
  declare included?: NoYes | null;
  /**
   * Survey Code.
   */
  declare surveyCode: DeserializedType<T, 'Edm.Int64'>;
  /**
   * Country Region Id.
   * @nullable
   */
  declare countryRegionId?: DeserializedType<T, 'Edm.String'> | null;
  /**
   * Country Region Group Blwi Reporting.
   * @nullable
   */
  declare countryRegionGroupBlwiReporting?: NoYes | null;
  /**
   * Amount.
   */
  declare amount: DeserializedType<T, 'Edm.Decimal'>;
  /**
   * Country Region Group Description.
   * @nullable
   */
  declare countryRegionGroupDescription?: DeserializedType<
    T,
    'Edm.String'
  > | null;
  /**
   * Country Region Name.
   * @nullable
   */
  declare countryRegionName?: DeserializedType<T, 'Edm.String'> | null;
  /**
   * Original Amount.
   */
  declare originalAmount: DeserializedType<T, 'Edm.Decimal'>;
  /**
   * Purpose Code.
   * @nullable
   */
  declare purposeCode?: DeserializedType<T, 'Edm.String'> | null;

  constructor(_entityApi: BlwiApi<T>) {
    super(_entityApi);
  }
}

export interface BlwiType<T extends DeSerializers = DefaultDeSerializers> {
  dataAreaId: DeserializedType<T, 'Edm.String'>;
  company: DeserializedType<T, 'Edm.String'>;
  blwiTransaction?: TradeBlwiCustVend | null;
  accountNumber: DeserializedType<T, 'Edm.String'>;
  voucher: DeserializedType<T, 'Edm.String'>;
  invoice: DeserializedType<T, 'Edm.String'>;
  transactionDate: DeserializedType<T, 'Edm.DateTimeOffset'>;
  amountInTransactionCurrency: DeserializedType<T, 'Edm.Decimal'>;
  reportingDate: DeserializedType<T, 'Edm.DateTimeOffset'>;
  autoGenerated?: NoYes | null;
  countryRegionGroupRowNumber: DeserializedType<T, 'Edm.Int32'>;
  currency?: DeserializedType<T, 'Edm.String'> | null;
  countryRegionGroupId?: DeserializedType<T, 'Edm.String'> | null;
  included?: NoYes | null;
  surveyCode: DeserializedType<T, 'Edm.Int64'>;
  countryRegionId?: DeserializedType<T, 'Edm.String'> | null;
  countryRegionGroupBlwiReporting?: NoYes | null;
  amount: DeserializedType<T, 'Edm.Decimal'>;
  countryRegionGroupDescription?: DeserializedType<T, 'Edm.String'> | null;
  countryRegionName?: DeserializedType<T, 'Edm.String'> | null;
  originalAmount: DeserializedType<T, 'Edm.Decimal'>;
  purposeCode?: DeserializedType<T, 'Edm.String'> | null;
}
