/*
 * Copyright (c) 2025 SAP SE or an SAP affiliate company. All rights reserved.
 *
 * This is a generated file powered by the SAP Cloud SDK for JavaScript.
 */
import {
  Entity,
  DefaultDeSerializers,
  DeSerializers,
  DeserializedType
} from '@sap-cloud-sdk/odata-v4';
import type { ExpCopilotAutomationExpensesApi } from './ExpCopilotAutomationExpensesApi';
import { NoYes } from './NoYes';
import { TrvExpGeneratedBy } from './TrvExpGeneratedBy';
import { TrvCarRentalVehicleClassEnum } from './TrvCarRentalVehicleClassEnum';
import { TrvExpEntryPoint } from './TrvExpEntryPoint';
import { TrvAirlineServiceClassEnum } from './TrvAirlineServiceClassEnum';
import { TrvBillIssuedTo } from './TrvBillIssuedTo';
import { TrvCostOwner } from './TrvCostOwner';
import { TrvExpLineType } from './TrvExpLineType';
import { Timezone } from './Timezone';
import { LedgerJournalAcType } from './LedgerJournalAcType';
import { TrvExpSplitLineType } from './TrvExpSplitLineType';
import { TrvExpType } from './TrvExpType';
import { TrvAppStatus } from './TrvAppStatus';
import { ProjExpPolicyStatus } from './ProjExpPolicyStatus';
import { DimensionSets, DimensionSetsType } from './DimensionSets';

/**
 * This class represents the entity "ExpCopilotAutomationExpenses" of service "d365_metadata".
 */
export class ExpCopilotAutomationExpenses<
    T extends DeSerializers = DefaultDeSerializers
  >
  extends Entity
  implements ExpCopilotAutomationExpensesType<T>
{
  /**
   * Technical entity name for ExpCopilotAutomationExpenses.
   */
  static override _entityName = 'ExpCopilotAutomationExpenses';
  /**
   * Default url path for the according service.
   */
  static override _defaultBasePath = '/';
  /**
   * All key fields of the ExpCopilotAutomationExpenses entity.
   */
  static _keys = ['dataAreaId', 'ExpTransNumber'];
  /**
   * Data Area Id.
   */
  declare dataAreaId: DeserializedType<T, 'Edm.String'>;
  /**
   * Exp Trans Number.
   */
  declare expTransNumber: DeserializedType<T, 'Edm.String'>;
  /**
   * Business Purpose.
   * @nullable
   */
  declare businessPurpose?: DeserializedType<T, 'Edm.String'> | null;
  /**
   * Is Submitter Justification Required.
   */
  declare isSubmitterJustificationRequired: DeserializedType<T, 'Edm.Int32'>;
  /**
   * Receipt Required.
   * @nullable
   */
  declare receiptRequired?: NoYes | null;
  /**
   * Voucher.
   * @nullable
   */
  declare voucher?: DeserializedType<T, 'Edm.String'> | null;
  /**
   * Trv Locations Country Region Id.
   * @nullable
   */
  declare trvLocationsCountryRegionId?: DeserializedType<
    T,
    'Edm.String'
  > | null;
  /**
   * Trv Exp Generated By.
   * @nullable
   */
  declare trvExpGeneratedBy?: TrvExpGeneratedBy | null;
  /**
   * Reimburse Amt.
   */
  declare reimburseAmt: DeserializedType<T, 'Edm.Decimal'>;
  /**
   * Km Own Car.
   */
  declare kmOwnCar: DeserializedType<T, 'Edm.Decimal'>;
  /**
   * Return Date.
   */
  declare returnDate: DeserializedType<T, 'Edm.DateTimeOffset'>;
  /**
   * Receipts Attached.
   * @nullable
   */
  declare receiptsAttached?: NoYes | null;
  /**
   * Policy Violation Message.
   * @nullable
   */
  declare policyViolationMessage?: DeserializedType<T, 'Edm.String'> | null;
  /**
   * Apply Action.
   * @nullable
   */
  declare applyAction?: NoYes | null;
  /**
   * Vehicle Class.
   * @nullable
   */
  declare vehicleClass?: TrvCarRentalVehicleClassEnum | null;
  /**
   * Mileage From Address.
   * @nullable
   */
  declare mileageFromAddress?: DeserializedType<T, 'Edm.String'> | null;
  /**
   * Ticket Used.
   * @nullable
   */
  declare ticketUsed?: NoYes | null;
  /**
   * Pay Method.
   * @nullable
   */
  declare payMethod?: DeserializedType<T, 'Edm.String'> | null;
  /**
   * Intercompany Billed.
   */
  declare intercompanyBilled: DeserializedType<T, 'Edm.Boolean'>;
  /**
   * Line Number.
   */
  declare lineNumber: DeserializedType<T, 'Edm.Decimal'>;
  /**
   * Credit Card Transaction Currency.
   * @nullable
   */
  declare creditCardTransactionCurrency?: DeserializedType<
    T,
    'Edm.String'
  > | null;
  /**
   * Proj Trans Id.
   * @nullable
   */
  declare projTransId?: DeserializedType<T, 'Edm.String'> | null;
  /**
   * Trv Locations.
   */
  declare trvLocations: DeserializedType<T, 'Edm.Int64'>;
  /**
   * Sub Category Rec Id.
   */
  declare subCategoryRecId: DeserializedType<T, 'Edm.Int64'>;
  /**
   * Country Region.
   * @nullable
   */
  declare countryRegion?: DeserializedType<T, 'Edm.String'> | null;
  /**
   * Not Approved Date.
   */
  declare notApprovedDate: DeserializedType<T, 'Edm.DateTimeOffset'>;
  /**
   * Proj Activity Number.
   * @nullable
   */
  declare projActivityNumber?: DeserializedType<T, 'Edm.String'> | null;
  /**
   * Tax Included.
   * @nullable
   */
  declare taxIncluded?: NoYes | null;
  /**
   * Exchange Code.
   * @nullable
   */
  declare exchangeCode?: DeserializedType<T, 'Edm.String'> | null;
  /**
   * Trans Date.
   */
  declare transDate: DeserializedType<T, 'Edm.DateTimeOffset'>;
  /**
   * Invoice Amt.
   */
  declare invoiceAmt: DeserializedType<T, 'Edm.Decimal'>;
  /**
   * Corrected Tax Amount.
   */
  declare correctedTaxAmount: DeserializedType<T, 'Edm.Decimal'>;
  /**
   * Entry Point.
   * @nullable
   */
  declare entryPoint?: TrvExpEntryPoint | null;
  /**
   * Default Dimension Display Value.
   * @nullable
   */
  declare defaultDimensionDisplayValue?: DeserializedType<
    T,
    'Edm.String'
  > | null;
  /**
   * Vat Due Date W.
   */
  declare vatDueDateW: DeserializedType<T, 'Edm.DateTimeOffset'>;
  /**
   * Ticket Number.
   * @nullable
   */
  declare ticketNumber?: DeserializedType<T, 'Edm.String'> | null;
  /**
   * Vehicle Type.
   * @nullable
   */
  declare vehicleType?: DeserializedType<T, 'Edm.String'> | null;
  /**
   * Net Transaction Amount.
   */
  declare netTransactionAmount: DeserializedType<T, 'Edm.Decimal'>;
  /**
   * Check Out Date.
   */
  declare checkOutDate: DeserializedType<T, 'Edm.DateTimeOffset'>;
  /**
   * Amount Mst.
   */
  declare amountMst: DeserializedType<T, 'Edm.Decimal'>;
  /**
   * Inter Company Le.
   * @nullable
   */
  declare interCompanyLe?: DeserializedType<T, 'Edm.String'> | null;
  /**
   * Service Class.
   * @nullable
   */
  declare serviceClass?: TrvAirlineServiceClassEnum | null;
  /**
   * Attached Receipt Id.
   * @nullable
   */
  declare attachedReceiptId?: DeserializedType<T, 'Edm.String'> | null;
  /**
   * Total Tax Amount.
   */
  declare totalTaxAmount: DeserializedType<T, 'Edm.Decimal'>;
  /**
   * Project Name.
   * @nullable
   */
  declare projectName?: DeserializedType<T, 'Edm.String'> | null;
  /**
   * Inter Company Category.
   * @nullable
   */
  declare interCompanyCategory?: DeserializedType<T, 'Edm.String'> | null;
  /**
   * Car Rental Check Out Date.
   */
  declare carRentalCheckOutDate: DeserializedType<T, 'Edm.DateTimeOffset'>;
  /**
   * Party Id.
   * @nullable
   */
  declare partyId?: DeserializedType<T, 'Edm.String'> | null;
  /**
   * Additional Information.
   * @nullable
   */
  declare additionalInformation?: DeserializedType<T, 'Edm.String'> | null;
  /**
   * Date From.
   */
  declare dateFrom: DeserializedType<T, 'Edm.DateTimeOffset'>;
  /**
   * City.
   * @nullable
   */
  declare city?: DeserializedType<T, 'Edm.String'> | null;
  /**
   * Tax Item Group.
   * @nullable
   */
  declare taxItemGroup?: DeserializedType<T, 'Edm.String'> | null;
  /**
   * Number Of Passengers.
   */
  declare numberOfPassengers: DeserializedType<T, 'Edm.Int32'>;
  /**
   * Expense Itemization Group Id.
   * @nullable
   */
  declare expenseItemizationGroupId?: DeserializedType<T, 'Edm.String'> | null;
  /**
   * Is Budget Check Pending.
   * @nullable
   */
  declare isBudgetCheckPending?: NoYes | null;
  /**
   * Travel Agency Name.
   * @nullable
   */
  declare travelAgencyName?: DeserializedType<T, 'Edm.String'> | null;
  /**
   * Transaction Text.
   * @nullable
   */
  declare transactionText?: DeserializedType<T, 'Edm.String'> | null;
  /**
   * Intercompany Sales Currency.
   * @nullable
   */
  declare intercompanySalesCurrency?: DeserializedType<T, 'Edm.String'> | null;
  /**
   * Merchant Id.
   * @nullable
   */
  declare merchantId?: DeserializedType<T, 'Edm.String'> | null;
  /**
   * Trv Locations Location.
   * @nullable
   */
  declare trvLocationsLocation?: DeserializedType<T, 'Edm.String'> | null;
  /**
   * Trv Hcm Worker Personnel Number.
   * @nullable
   */
  declare trvHcmWorkerPersonnelNumber?: DeserializedType<
    T,
    'Edm.String'
  > | null;
  /**
   * Detach Unattached Rec Id.
   */
  declare detachUnattachedRecId: DeserializedType<T, 'Edm.Int32'>;
  /**
   * Legal Entity 1 Data Area.
   * @nullable
   */
  declare legalEntity1DataArea?: DeserializedType<T, 'Edm.String'> | null;
  /**
   * Bill Issued To.
   * @nullable
   */
  declare billIssuedTo?: TrvBillIssuedTo | null;
  /**
   * Check Out Location.
   * @nullable
   */
  declare checkOutLocation?: DeserializedType<T, 'Edm.String'> | null;
  /**
   * Credit Card Transaction Currency Amount.
   */
  declare creditCardTransactionCurrencyAmount: DeserializedType<
    T,
    'Edm.Decimal'
  >;
  /**
   * Address State.
   * @nullable
   */
  declare addressState?: DeserializedType<T, 'Edm.String'> | null;
  /**
   * Cost Owner.
   * @nullable
   */
  declare costOwner?: TrvCostOwner | null;
  /**
   * Agent Worker Id.
   */
  declare agentWorkerId: DeserializedType<T, 'Edm.Int64'>;
  /**
   * Description.
   * @nullable
   */
  declare description?: DeserializedType<T, 'Edm.String'> | null;
  /**
   * Line Type.
   * @nullable
   */
  declare lineType?: TrvExpLineType | null;
  /**
   * Justifying Worker.
   */
  declare justifyingWorker: DeserializedType<T, 'Edm.Int64'>;
  /**
   * Policy Violation Error Message.
   * @nullable
   */
  declare policyViolationErrorMessage?: DeserializedType<
    T,
    'Edm.String'
  > | null;
  /**
   * Is Pre Authorized.
   * @nullable
   */
  declare isPreAuthorized?: NoYes | null;
  /**
   * Amount Currency.
   * @nullable
   */
  declare amountCurrency?: DeserializedType<T, 'Edm.String'> | null;
  /**
   * Address Zip Code.
   */
  declare addressZipCode: DeserializedType<T, 'Edm.Int64'>;
  /**
   * Perdiem Timezone.
   * @nullable
   */
  declare perdiemTimezone?: Timezone | null;
  /**
   * Intercompany Transfer Currency.
   * @nullable
   */
  declare intercompanyTransferCurrency?: DeserializedType<
    T,
    'Edm.String'
  > | null;
  /**
   * Ticket Issue Date.
   */
  declare ticketIssueDate: DeserializedType<T, 'Edm.DateTimeOffset'>;
  /**
   * Deduktion Lunch.
   */
  declare deduktionLunch: DeserializedType<T, 'Edm.Int32'>;
  /**
   * Total Room Rent.
   */
  declare totalRoomRent: DeserializedType<T, 'Edm.Decimal'>;
  /**
   * Per Diem Hotel Allowance.
   */
  declare perDiemHotelAllowance: DeserializedType<T, 'Edm.Decimal'>;
  /**
   * Accounting Currency Over Budget Amount.
   */
  declare accountingCurrencyOverBudgetAmount: DeserializedType<
    T,
    'Edm.Decimal'
  >;
  /**
   * Sub Category Cost Type.
   * @nullable
   */
  declare subCategoryCostType?: DeserializedType<T, 'Edm.String'> | null;
  /**
   * Post Account Type.
   * @nullable
   */
  declare postAccountType?: LedgerJournalAcType | null;
  /**
   * Unattached Receipt Rec Ids.
   * @nullable
   */
  declare unattachedReceiptRecIds?: DeserializedType<T, 'Edm.String'> | null;
  /**
   * Amount Curr.
   */
  declare amountCurr: DeserializedType<T, 'Edm.Decimal'>;
  /**
   * Intercompany Sales Price.
   */
  declare intercompanySalesPrice: DeserializedType<T, 'Edm.Decimal'>;
  /**
   * Is Creditcard Transaction In Local Currency.
   * @nullable
   */
  declare isCreditcardTransactionInLocalCurrency?: NoYes | null;
  /**
   * Proj Status Id.
   * @nullable
   */
  declare projStatusId?: DeserializedType<T, 'Edm.String'> | null;
  /**
   * Tax Group.
   * @nullable
   */
  declare taxGroup?: DeserializedType<T, 'Edm.String'> | null;
  /**
   * Travel Agency Invoice Number.
   * @nullable
   */
  declare travelAgencyInvoiceNumber?: DeserializedType<T, 'Edm.String'> | null;
  /**
   * Deduktion Mst.
   */
  declare deduktionMst: DeserializedType<T, 'Edm.Decimal'>;
  /**
   * Exchange Rate.
   */
  declare exchangeRate: DeserializedType<T, 'Edm.Decimal'>;
  /**
   * Itemized Line Exp Trans Number.
   * @nullable
   */
  declare itemizedLineExpTransNumber?: DeserializedType<T, 'Edm.String'> | null;
  /**
   * Corrected Tax Amount Mst.
   */
  declare correctedTaxAmountMst: DeserializedType<T, 'Edm.Decimal'>;
  /**
   * Trv Locations State Id.
   * @nullable
   */
  declare trvLocationsStateId?: DeserializedType<T, 'Edm.String'> | null;
  /**
   * Proj Policy Text.
   * @nullable
   */
  declare projPolicyText?: DeserializedType<T, 'Edm.String'> | null;
  /**
   * Trans Row Num.
   */
  declare transRowNum: DeserializedType<T, 'Edm.Int32'>;
  /**
   * Creating Worker.
   */
  declare creatingWorker: DeserializedType<T, 'Edm.Int64'>;
  /**
   * Line Level Posting.
   * @nullable
   */
  declare lineLevelPosting?: NoYes | null;
  /**
   * Deduktion Dinner.
   */
  declare deduktionDinner: DeserializedType<T, 'Edm.Int32'>;
  /**
   * Mobile Statement.
   * @nullable
   */
  declare mobileStatement?: NoYes | null;
  /**
   * Post Account.
   * @nullable
   */
  declare postAccount?: DeserializedType<T, 'Edm.String'> | null;
  /**
   * Total Room Nights.
   */
  declare totalRoomNights: DeserializedType<T, 'Edm.Int32'>;
  /**
   * Trv Shared Sub Category Name.
   * @nullable
   */
  declare trvSharedSubCategoryName?: DeserializedType<T, 'Edm.String'> | null;
  /**
   * Expense Rec Id.
   */
  declare expenseRecId: DeserializedType<T, 'Edm.Int64'>;
  /**
   * Check In Date.
   */
  declare checkInDate: DeserializedType<T, 'Edm.DateTimeOffset'>;
  /**
   * Cash Advance Cash Advance Number.
   * @nullable
   */
  declare cashAdvanceCashAdvanceNumber?: DeserializedType<
    T,
    'Edm.String'
  > | null;
  /**
   * Cost Type.
   * @nullable
   */
  declare costType?: DeserializedType<T, 'Edm.String'> | null;
  /**
   * Intercompany Transfer Price.
   */
  declare intercompanyTransferPrice: DeserializedType<T, 'Edm.Decimal'>;
  /**
   * Reference Data Area Id.
   * @nullable
   */
  declare referenceDataAreaId?: DeserializedType<T, 'Edm.String'> | null;
  /**
   * Date To.
   */
  declare dateTo: DeserializedType<T, 'Edm.DateTimeOffset'>;
  /**
   * Split Line Type.
   * @nullable
   */
  declare splitLineType?: TrvExpSplitLineType | null;
  /**
   * Km Price.
   */
  declare kmPrice: DeserializedType<T, 'Edm.Decimal'>;
  /**
   * Original Receipts Recvd.
   * @nullable
   */
  declare originalReceiptsRecvd?: NoYes | null;
  /**
   * Accounting Currency Reconciled Amount.
   */
  declare accountingCurrencyReconciledAmount: DeserializedType<
    T,
    'Edm.Decimal'
  >;
  /**
   * Deduktion.
   */
  declare deduktion: DeserializedType<T, 'Edm.Decimal'>;
  /**
   * Meal And Incidentals.
   */
  declare mealAndIncidentals: DeserializedType<T, 'Edm.Decimal'>;
  /**
   * Trv Exp Table Rec Id Exp Number.
   * @nullable
   */
  declare trvExpTableRecIdExpNumber?: DeserializedType<T, 'Edm.String'> | null;
  /**
   * Address City Name.
   * @nullable
   */
  declare addressCityName?: DeserializedType<T, 'Edm.String'> | null;
  /**
   * Exp Type.
   * @nullable
   */
  declare expType?: TrvExpType | null;
  /**
   * Is Split.
   * @nullable
   */
  declare isSplit?: NoYes | null;
  /**
   * Domestic Indicator.
   * @nullable
   */
  declare domesticIndicator?: NoYes | null;
  /**
   * Deduktion Breakfest.
   */
  declare deduktionBreakfest: DeserializedType<T, 'Edm.Int32'>;
  /**
   * Approval Status.
   * @nullable
   */
  declare approvalStatus?: TrvAppStatus | null;
  /**
   * Proj Id.
   * @nullable
   */
  declare projId?: DeserializedType<T, 'Edm.String'> | null;
  /**
   * Receipt Number.
   * @nullable
   */
  declare receiptNumber?: DeserializedType<T, 'Edm.String'> | null;
  /**
   * Company.
   * @nullable
   */
  declare company?: DeserializedType<T, 'Edm.String'> | null;
  /**
   * Proj Policy Status.
   * @nullable
   */
  declare projPolicyStatus?: ProjExpPolicyStatus | null;
  /**
   * Reason.
   * @nullable
   */
  declare reason?: DeserializedType<T, 'Edm.String'> | null;
  /**
   * Pbs Statement.
   * @nullable
   */
  declare pbsStatement?: NoYes | null;
  /**
   * Policy Violation Count.
   */
  declare policyViolationCount: DeserializedType<T, 'Edm.Int64'>;
  /**
   * Approved Date.
   */
  declare approvedDate: DeserializedType<T, 'Edm.DateTimeOffset'>;
  /**
   * Mileage To Address.
   * @nullable
   */
  declare mileageToAddress?: DeserializedType<T, 'Edm.String'> | null;
  /**
   * Posting Errors.
   * @nullable
   */
  declare postingErrors?: DeserializedType<T, 'Edm.String'> | null;
  /**
   * Policy Violations Level.
   */
  declare policyViolationsLevel: DeserializedType<T, 'Edm.Int64'>;
  /**
   * Submitter Justification.
   * @nullable
   */
  declare submitterJustification?: DeserializedType<T, 'Edm.String'> | null;
  /**
   * Ticket Class.
   * @nullable
   */
  declare ticketClass?: DeserializedType<T, 'Edm.String'> | null;
  /**
   * Detach.
   */
  declare detach: DeserializedType<T, 'Edm.Int32'>;
  /**
   * Entertainment Location.
   * @nullable
   */
  declare entertainmentLocation?: DeserializedType<T, 'Edm.String'> | null;
  /**
   * Legal Entity 1 Party Number.
   * @nullable
   */
  declare legalEntity1PartyNumber?: DeserializedType<T, 'Edm.String'> | null;
  /**
   * Document Created Date Time.
   */
  declare documentCreatedDateTime: DeserializedType<T, 'Edm.DateTimeOffset'>;
  /**
   * Exp Number.
   * @nullable
   */
  declare expNumber?: DeserializedType<T, 'Edm.String'> | null;
  /**
   * One-to-one navigation property to the {@link DimensionSets} entity.
   */
  declare dimensionSet?: DimensionSets<T> | null;

  constructor(_entityApi: ExpCopilotAutomationExpensesApi<T>) {
    super(_entityApi);
  }
}

export interface ExpCopilotAutomationExpensesType<
  T extends DeSerializers = DefaultDeSerializers
> {
  dataAreaId: DeserializedType<T, 'Edm.String'>;
  expTransNumber: DeserializedType<T, 'Edm.String'>;
  businessPurpose?: DeserializedType<T, 'Edm.String'> | null;
  isSubmitterJustificationRequired: DeserializedType<T, 'Edm.Int32'>;
  receiptRequired?: NoYes | null;
  voucher?: DeserializedType<T, 'Edm.String'> | null;
  trvLocationsCountryRegionId?: DeserializedType<T, 'Edm.String'> | null;
  trvExpGeneratedBy?: TrvExpGeneratedBy | null;
  reimburseAmt: DeserializedType<T, 'Edm.Decimal'>;
  kmOwnCar: DeserializedType<T, 'Edm.Decimal'>;
  returnDate: DeserializedType<T, 'Edm.DateTimeOffset'>;
  receiptsAttached?: NoYes | null;
  policyViolationMessage?: DeserializedType<T, 'Edm.String'> | null;
  applyAction?: NoYes | null;
  vehicleClass?: TrvCarRentalVehicleClassEnum | null;
  mileageFromAddress?: DeserializedType<T, 'Edm.String'> | null;
  ticketUsed?: NoYes | null;
  payMethod?: DeserializedType<T, 'Edm.String'> | null;
  intercompanyBilled: DeserializedType<T, 'Edm.Boolean'>;
  lineNumber: DeserializedType<T, 'Edm.Decimal'>;
  creditCardTransactionCurrency?: DeserializedType<T, 'Edm.String'> | null;
  projTransId?: DeserializedType<T, 'Edm.String'> | null;
  trvLocations: DeserializedType<T, 'Edm.Int64'>;
  subCategoryRecId: DeserializedType<T, 'Edm.Int64'>;
  countryRegion?: DeserializedType<T, 'Edm.String'> | null;
  notApprovedDate: DeserializedType<T, 'Edm.DateTimeOffset'>;
  projActivityNumber?: DeserializedType<T, 'Edm.String'> | null;
  taxIncluded?: NoYes | null;
  exchangeCode?: DeserializedType<T, 'Edm.String'> | null;
  transDate: DeserializedType<T, 'Edm.DateTimeOffset'>;
  invoiceAmt: DeserializedType<T, 'Edm.Decimal'>;
  correctedTaxAmount: DeserializedType<T, 'Edm.Decimal'>;
  entryPoint?: TrvExpEntryPoint | null;
  defaultDimensionDisplayValue?: DeserializedType<T, 'Edm.String'> | null;
  vatDueDateW: DeserializedType<T, 'Edm.DateTimeOffset'>;
  ticketNumber?: DeserializedType<T, 'Edm.String'> | null;
  vehicleType?: DeserializedType<T, 'Edm.String'> | null;
  netTransactionAmount: DeserializedType<T, 'Edm.Decimal'>;
  checkOutDate: DeserializedType<T, 'Edm.DateTimeOffset'>;
  amountMst: DeserializedType<T, 'Edm.Decimal'>;
  interCompanyLe?: DeserializedType<T, 'Edm.String'> | null;
  serviceClass?: TrvAirlineServiceClassEnum | null;
  attachedReceiptId?: DeserializedType<T, 'Edm.String'> | null;
  totalTaxAmount: DeserializedType<T, 'Edm.Decimal'>;
  projectName?: DeserializedType<T, 'Edm.String'> | null;
  interCompanyCategory?: DeserializedType<T, 'Edm.String'> | null;
  carRentalCheckOutDate: DeserializedType<T, 'Edm.DateTimeOffset'>;
  partyId?: DeserializedType<T, 'Edm.String'> | null;
  additionalInformation?: DeserializedType<T, 'Edm.String'> | null;
  dateFrom: DeserializedType<T, 'Edm.DateTimeOffset'>;
  city?: DeserializedType<T, 'Edm.String'> | null;
  taxItemGroup?: DeserializedType<T, 'Edm.String'> | null;
  numberOfPassengers: DeserializedType<T, 'Edm.Int32'>;
  expenseItemizationGroupId?: DeserializedType<T, 'Edm.String'> | null;
  isBudgetCheckPending?: NoYes | null;
  travelAgencyName?: DeserializedType<T, 'Edm.String'> | null;
  transactionText?: DeserializedType<T, 'Edm.String'> | null;
  intercompanySalesCurrency?: DeserializedType<T, 'Edm.String'> | null;
  merchantId?: DeserializedType<T, 'Edm.String'> | null;
  trvLocationsLocation?: DeserializedType<T, 'Edm.String'> | null;
  trvHcmWorkerPersonnelNumber?: DeserializedType<T, 'Edm.String'> | null;
  detachUnattachedRecId: DeserializedType<T, 'Edm.Int32'>;
  legalEntity1DataArea?: DeserializedType<T, 'Edm.String'> | null;
  billIssuedTo?: TrvBillIssuedTo | null;
  checkOutLocation?: DeserializedType<T, 'Edm.String'> | null;
  creditCardTransactionCurrencyAmount: DeserializedType<T, 'Edm.Decimal'>;
  addressState?: DeserializedType<T, 'Edm.String'> | null;
  costOwner?: TrvCostOwner | null;
  agentWorkerId: DeserializedType<T, 'Edm.Int64'>;
  description?: DeserializedType<T, 'Edm.String'> | null;
  lineType?: TrvExpLineType | null;
  justifyingWorker: DeserializedType<T, 'Edm.Int64'>;
  policyViolationErrorMessage?: DeserializedType<T, 'Edm.String'> | null;
  isPreAuthorized?: NoYes | null;
  amountCurrency?: DeserializedType<T, 'Edm.String'> | null;
  addressZipCode: DeserializedType<T, 'Edm.Int64'>;
  perdiemTimezone?: Timezone | null;
  intercompanyTransferCurrency?: DeserializedType<T, 'Edm.String'> | null;
  ticketIssueDate: DeserializedType<T, 'Edm.DateTimeOffset'>;
  deduktionLunch: DeserializedType<T, 'Edm.Int32'>;
  totalRoomRent: DeserializedType<T, 'Edm.Decimal'>;
  perDiemHotelAllowance: DeserializedType<T, 'Edm.Decimal'>;
  accountingCurrencyOverBudgetAmount: DeserializedType<T, 'Edm.Decimal'>;
  subCategoryCostType?: DeserializedType<T, 'Edm.String'> | null;
  postAccountType?: LedgerJournalAcType | null;
  unattachedReceiptRecIds?: DeserializedType<T, 'Edm.String'> | null;
  amountCurr: DeserializedType<T, 'Edm.Decimal'>;
  intercompanySalesPrice: DeserializedType<T, 'Edm.Decimal'>;
  isCreditcardTransactionInLocalCurrency?: NoYes | null;
  projStatusId?: DeserializedType<T, 'Edm.String'> | null;
  taxGroup?: DeserializedType<T, 'Edm.String'> | null;
  travelAgencyInvoiceNumber?: DeserializedType<T, 'Edm.String'> | null;
  deduktionMst: DeserializedType<T, 'Edm.Decimal'>;
  exchangeRate: DeserializedType<T, 'Edm.Decimal'>;
  itemizedLineExpTransNumber?: DeserializedType<T, 'Edm.String'> | null;
  correctedTaxAmountMst: DeserializedType<T, 'Edm.Decimal'>;
  trvLocationsStateId?: DeserializedType<T, 'Edm.String'> | null;
  projPolicyText?: DeserializedType<T, 'Edm.String'> | null;
  transRowNum: DeserializedType<T, 'Edm.Int32'>;
  creatingWorker: DeserializedType<T, 'Edm.Int64'>;
  lineLevelPosting?: NoYes | null;
  deduktionDinner: DeserializedType<T, 'Edm.Int32'>;
  mobileStatement?: NoYes | null;
  postAccount?: DeserializedType<T, 'Edm.String'> | null;
  totalRoomNights: DeserializedType<T, 'Edm.Int32'>;
  trvSharedSubCategoryName?: DeserializedType<T, 'Edm.String'> | null;
  expenseRecId: DeserializedType<T, 'Edm.Int64'>;
  checkInDate: DeserializedType<T, 'Edm.DateTimeOffset'>;
  cashAdvanceCashAdvanceNumber?: DeserializedType<T, 'Edm.String'> | null;
  costType?: DeserializedType<T, 'Edm.String'> | null;
  intercompanyTransferPrice: DeserializedType<T, 'Edm.Decimal'>;
  referenceDataAreaId?: DeserializedType<T, 'Edm.String'> | null;
  dateTo: DeserializedType<T, 'Edm.DateTimeOffset'>;
  splitLineType?: TrvExpSplitLineType | null;
  kmPrice: DeserializedType<T, 'Edm.Decimal'>;
  originalReceiptsRecvd?: NoYes | null;
  accountingCurrencyReconciledAmount: DeserializedType<T, 'Edm.Decimal'>;
  deduktion: DeserializedType<T, 'Edm.Decimal'>;
  mealAndIncidentals: DeserializedType<T, 'Edm.Decimal'>;
  trvExpTableRecIdExpNumber?: DeserializedType<T, 'Edm.String'> | null;
  addressCityName?: DeserializedType<T, 'Edm.String'> | null;
  expType?: TrvExpType | null;
  isSplit?: NoYes | null;
  domesticIndicator?: NoYes | null;
  deduktionBreakfest: DeserializedType<T, 'Edm.Int32'>;
  approvalStatus?: TrvAppStatus | null;
  projId?: DeserializedType<T, 'Edm.String'> | null;
  receiptNumber?: DeserializedType<T, 'Edm.String'> | null;
  company?: DeserializedType<T, 'Edm.String'> | null;
  projPolicyStatus?: ProjExpPolicyStatus | null;
  reason?: DeserializedType<T, 'Edm.String'> | null;
  pbsStatement?: NoYes | null;
  policyViolationCount: DeserializedType<T, 'Edm.Int64'>;
  approvedDate: DeserializedType<T, 'Edm.DateTimeOffset'>;
  mileageToAddress?: DeserializedType<T, 'Edm.String'> | null;
  postingErrors?: DeserializedType<T, 'Edm.String'> | null;
  policyViolationsLevel: DeserializedType<T, 'Edm.Int64'>;
  submitterJustification?: DeserializedType<T, 'Edm.String'> | null;
  ticketClass?: DeserializedType<T, 'Edm.String'> | null;
  detach: DeserializedType<T, 'Edm.Int32'>;
  entertainmentLocation?: DeserializedType<T, 'Edm.String'> | null;
  legalEntity1PartyNumber?: DeserializedType<T, 'Edm.String'> | null;
  documentCreatedDateTime: DeserializedType<T, 'Edm.DateTimeOffset'>;
  expNumber?: DeserializedType<T, 'Edm.String'> | null;
  dimensionSet?: DimensionSetsType<T> | null;
}
