/*
 * Copyright (c) 2025 SAP SE or an SAP affiliate company. All rights reserved.
 *
 * This is a generated file powered by the SAP Cloud SDK for JavaScript.
 */
import {
  Entity,
  DefaultDeSerializers,
  DeSerializers,
  DeserializedType
} from '@sap-cloud-sdk/odata-v4';
import type { VendInvoiceInfoLineBiEntitiesApi } from './VendInvoiceInfoLineBiEntitiesApi';
import { NoYes } from './NoYes';
import { PurchInvoiceLineType } from './PurchInvoiceLineType';
import { VendInvoiceRequestStatus } from './VendInvoiceRequestStatus';

/**
 * This class represents the entity "VendInvoiceInfoLineBiEntities" of service "d365_metadata".
 */
export class VendInvoiceInfoLineBiEntities<
    T extends DeSerializers = DefaultDeSerializers
  >
  extends Entity
  implements VendInvoiceInfoLineBiEntitiesType<T>
{
  /**
   * Technical entity name for VendInvoiceInfoLineBiEntities.
   */
  static override _entityName = 'VendInvoiceInfoLineBiEntities';
  /**
   * Default url path for the according service.
   */
  static override _defaultBasePath = '/';
  /**
   * All key fields of the VendInvoiceInfoLineBiEntities entity.
   */
  static _keys = ['dataAreaId', 'SourceKey'];
  /**
   * Data Area Id.
   */
  declare dataAreaId: DeserializedType<T, 'Edm.String'>;
  /**
   * Source Key.
   */
  declare sourceKey: DeserializedType<T, 'Edm.Int64'>;
  /**
   * Advance Application Id.
   */
  declare advanceApplicationId: DeserializedType<T, 'Edm.Int64'>;
  /**
   * Vend Directive Psn.
   */
  declare vendDirectivePsn: DeserializedType<T, 'Edm.Int64'>;
  /**
   * Delivery Postal Address.
   */
  declare deliveryPostalAddress: DeserializedType<T, 'Edm.Int64'>;
  /**
   * Purch Commitment Line Psn.
   */
  declare purchCommitmentLinePsn: DeserializedType<T, 'Edm.Int64'>;
  /**
   * Closed.
   * @nullable
   */
  declare closed?: NoYes | null;
  /**
   * Remain Before Invent.
   */
  declare remainBeforeInvent: DeserializedType<T, 'Edm.Decimal'>;
  /**
   * Psa Release Percent.
   */
  declare psaReleasePercent: DeserializedType<T, 'Edm.Decimal'>;
  /**
   * Transport.
   * @nullable
   */
  declare transport?: DeserializedType<T, 'Edm.String'> | null;
  /**
   * Purch Markup.
   */
  declare purchMarkup: DeserializedType<T, 'Edm.Decimal'>;
  /**
   * Payroll Ledger Dimension Values Json.
   * @nullable
   */
  declare payrollLedgerDimensionValuesJson?: DeserializedType<
    T,
    'Edm.String'
  > | null;
  /**
   * Pds Calculation Id.
   * @nullable
   */
  declare pdsCalculationId?: DeserializedType<T, 'Edm.String'> | null;
  /**
   * Reason Table Ref.
   */
  declare reasonTableRef: DeserializedType<T, 'Edm.Int64'>;
  /**
   * Sys Data Area Id.
   * @nullable
   */
  declare sysDataAreaId?: DeserializedType<T, 'Edm.String'> | null;
  /**
   * Orig Purch Id.
   * @nullable
   */
  declare origPurchId?: DeserializedType<T, 'Edm.String'> | null;
  /**
   * Purch Unit.
   * @nullable
   */
  declare purchUnit?: DeserializedType<T, 'Edm.String'> | null;
  /**
   * Pds Calculated Unit Price.
   */
  declare pdsCalculatedUnitPrice: DeserializedType<T, 'Edm.Decimal'>;
  /**
   * Accounting Distribution Template.
   */
  declare accountingDistributionTemplate: DeserializedType<T, 'Edm.Int64'>;
  /**
   * Is Autogenerated.
   * @nullable
   */
  declare isAutogenerated?: NoYes | null;
  /**
   * Invoice Account.
   * @nullable
   */
  declare invoiceAccount?: DeserializedType<T, 'Edm.String'> | null;
  /**
   * Price Unit.
   */
  declare priceUnit: DeserializedType<T, 'Edm.Decimal'>;
  /**
   * Invent Dim Id.
   * @nullable
   */
  declare inventDimId?: DeserializedType<T, 'Edm.String'> | null;
  /**
   * Tax Withhold Group.
   * @nullable
   */
  declare taxWithholdGroup?: DeserializedType<T, 'Edm.String'> | null;
  /**
   * Psa Is Final.
   * @nullable
   */
  declare psaIsFinal?: NoYes | null;
  /**
   * Line Disc.
   */
  declare lineDisc: DeserializedType<T, 'Edm.Decimal'>;
  /**
   * Multi Ln Disc.
   */
  declare multiLnDisc: DeserializedType<T, 'Edm.Decimal'>;
  /**
   * Purchase Line Line Number.
   */
  declare purchaseLineLineNumber: DeserializedType<T, 'Edm.Int64'>;
  /**
   * Tax 1099 Box Detail.
   */
  declare tax1099BoxDetail: DeserializedType<T, 'Edm.Int64'>;
  /**
   * Description.
   * @nullable
   */
  declare description?: DeserializedType<T, 'Edm.String'> | null;
  /**
   * Pds Cw Receive Now.
   */
  declare pdsCwReceiveNow: DeserializedType<T, 'Edm.Decimal'>;
  /**
   * Agreement Line Psn.
   */
  declare agreementLinePsn: DeserializedType<T, 'Edm.Int64'>;
  /**
   * Tax 1099 Fields.
   */
  declare tax1099Fields: DeserializedType<T, 'Edm.Int64'>;
  /**
   * Address Ref Table Id.
   */
  declare addressRefTableId: DeserializedType<T, 'Edm.Int32'>;
  /**
   * Orig Country Region Id.
   * @nullable
   */
  declare origCountryRegionId?: DeserializedType<T, 'Edm.String'> | null;
  /**
   * Line Type.
   * @nullable
   */
  declare lineType?: PurchInvoiceLineType | null;
  /**
   * Remain After.
   */
  declare remainAfter: DeserializedType<T, 'Edm.Decimal'>;
  /**
   * Sys Rec Version.
   */
  declare sysRecVersion: DeserializedType<T, 'Edm.Int32'>;
  /**
   * Psa Retainage Percent.
   */
  declare psaRetainagePercent: DeserializedType<T, 'Edm.Decimal'>;
  /**
   * Order Account.
   * @nullable
   */
  declare orderAccount?: DeserializedType<T, 'Edm.String'> | null;
  /**
   * Purch Price.
   */
  declare purchPrice: DeserializedType<T, 'Edm.Decimal'>;
  /**
   * County Orig Dest.
   * @nullable
   */
  declare countyOrigDest?: DeserializedType<T, 'Edm.String'> | null;
  /**
   * Orig State Id.
   * @nullable
   */
  declare origStateId?: DeserializedType<T, 'Edm.String'> | null;
  /**
   * Address Ref Rec Id.
   */
  declare addressRefRecId: DeserializedType<T, 'Edm.Int64'>;
  /**
   * Remain Before.
   */
  declare remainBefore: DeserializedType<T, 'Edm.Decimal'>;
  /**
   * Line Amount.
   */
  declare lineAmount: DeserializedType<T, 'Edm.Decimal'>;
  /**
   * Psa Release Amount.
   */
  declare psaReleaseAmount: DeserializedType<T, 'Edm.Decimal'>;
  /**
   * Pds Cw Remain After.
   */
  declare pdsCwRemainAfter: DeserializedType<T, 'Edm.Decimal'>;
  /**
   * Tax 1099 State.
   * @nullable
   */
  declare tax1099State?: DeserializedType<T, 'Edm.String'> | null;
  /**
   * Pds Cw Remain Before.
   */
  declare pdsCwRemainBefore: DeserializedType<T, 'Edm.Decimal'>;
  /**
   * Request Status.
   * @nullable
   */
  declare requestStatus?: VendInvoiceRequestStatus | null;
  /**
   * Psa Retainage Amount.
   */
  declare psaRetainageAmount: DeserializedType<T, 'Edm.Decimal'>;
  /**
   * Purch Line Rec Id.
   */
  declare purchLineRecId: DeserializedType<T, 'Edm.Int64'>;
  /**
   * Tax Group.
   * @nullable
   */
  declare taxGroup?: DeserializedType<T, 'Edm.String'> | null;
  /**
   * Parm Id.
   * @nullable
   */
  declare parmId?: DeserializedType<T, 'Edm.String'> | null;
  /**
   * Tax Withhold Item Group Heading Id.
   */
  declare taxWithholdItemGroupHeadingId: DeserializedType<T, 'Edm.Int64'>;
  /**
   * Psa Retainage Balance.
   */
  declare psaRetainageBalance: DeserializedType<T, 'Edm.Decimal'>;
  /**
   * Tax 1099 State Amount.
   */
  declare tax1099StateAmount: DeserializedType<T, 'Edm.Decimal'>;
  /**
   * Intrastat Commodity.
   */
  declare intrastatCommodity: DeserializedType<T, 'Edm.Int64'>;
  /**
   * Source Document Line.
   */
  declare sourceDocumentLine: DeserializedType<T, 'Edm.Int64'>;
  /**
   * Changed Manually.
   * @nullable
   */
  declare changedManually?: NoYes | null;
  /**
   * Line Num.
   */
  declare lineNum: DeserializedType<T, 'Edm.Decimal'>;
  /**
   * Currency Code.
   * @nullable
   */
  declare currencyCode?: DeserializedType<T, 'Edm.String'> | null;
  /**
   * Procurement Category.
   */
  declare procurementCategory: DeserializedType<T, 'Edm.Int64'>;
  /**
   * Item Id.
   * @nullable
   */
  declare itemId?: DeserializedType<T, 'Edm.String'> | null;
  /**
   * Tax 1099 Amount.
   */
  declare tax1099Amount: DeserializedType<T, 'Edm.Decimal'>;
  /**
   * Override Sales Tax.
   * @nullable
   */
  declare overrideSalesTax?: NoYes | null;
  /**
   * Remain After Invent.
   */
  declare remainAfterInvent: DeserializedType<T, 'Edm.Decimal'>;
  /**
   * Multi Ln Percent.
   */
  declare multiLnPercent: DeserializedType<T, 'Edm.Decimal'>;
  /**
   * Tax Item Group.
   * @nullable
   */
  declare taxItemGroup?: DeserializedType<T, 'Edm.String'> | null;
  /**
   * Receive Now.
   */
  declare receiveNow: DeserializedType<T, 'Edm.Decimal'>;
  /**
   * Stat Proc Id.
   * @nullable
   */
  declare statProcId?: DeserializedType<T, 'Edm.String'> | null;
  /**
   * Remain Before Invent Physical.
   */
  declare remainBeforeInventPhysical: DeserializedType<T, 'Edm.Decimal'>;
  /**
   * Table Ref Id.
   * @nullable
   */
  declare tableRefId?: DeserializedType<T, 'Edm.String'> | null;
  /**
   * Budget Reservation Line Psn.
   */
  declare budgetReservationLinePsn: DeserializedType<T, 'Edm.Int64'>;
  /**
   * Transaction Code.
   * @nullable
   */
  declare transactionCode?: DeserializedType<T, 'Edm.String'> | null;
  /**
   * Invent Now.
   */
  declare inventNow: DeserializedType<T, 'Edm.Decimal'>;
  /**
   * Line Percent.
   */
  declare linePercent: DeserializedType<T, 'Edm.Decimal'>;
  /**
   * Invoice Line Num.
   */
  declare invoiceLineNum: DeserializedType<T, 'Edm.Decimal'>;
  /**
   * Delivery Name.
   * @nullable
   */
  declare deliveryName?: DeserializedType<T, 'Edm.String'> | null;
  /**
   * Invent Trans Id.
   * @nullable
   */
  declare inventTransId?: DeserializedType<T, 'Edm.String'> | null;
  /**
   * Port.
   * @nullable
   */
  declare port?: DeserializedType<T, 'Edm.String'> | null;

  constructor(_entityApi: VendInvoiceInfoLineBiEntitiesApi<T>) {
    super(_entityApi);
  }
}

export interface VendInvoiceInfoLineBiEntitiesType<
  T extends DeSerializers = DefaultDeSerializers
> {
  dataAreaId: DeserializedType<T, 'Edm.String'>;
  sourceKey: DeserializedType<T, 'Edm.Int64'>;
  advanceApplicationId: DeserializedType<T, 'Edm.Int64'>;
  vendDirectivePsn: DeserializedType<T, 'Edm.Int64'>;
  deliveryPostalAddress: DeserializedType<T, 'Edm.Int64'>;
  purchCommitmentLinePsn: DeserializedType<T, 'Edm.Int64'>;
  closed?: NoYes | null;
  remainBeforeInvent: DeserializedType<T, 'Edm.Decimal'>;
  psaReleasePercent: DeserializedType<T, 'Edm.Decimal'>;
  transport?: DeserializedType<T, 'Edm.String'> | null;
  purchMarkup: DeserializedType<T, 'Edm.Decimal'>;
  payrollLedgerDimensionValuesJson?: DeserializedType<T, 'Edm.String'> | null;
  pdsCalculationId?: DeserializedType<T, 'Edm.String'> | null;
  reasonTableRef: DeserializedType<T, 'Edm.Int64'>;
  sysDataAreaId?: DeserializedType<T, 'Edm.String'> | null;
  origPurchId?: DeserializedType<T, 'Edm.String'> | null;
  purchUnit?: DeserializedType<T, 'Edm.String'> | null;
  pdsCalculatedUnitPrice: DeserializedType<T, 'Edm.Decimal'>;
  accountingDistributionTemplate: DeserializedType<T, 'Edm.Int64'>;
  isAutogenerated?: NoYes | null;
  invoiceAccount?: DeserializedType<T, 'Edm.String'> | null;
  priceUnit: DeserializedType<T, 'Edm.Decimal'>;
  inventDimId?: DeserializedType<T, 'Edm.String'> | null;
  taxWithholdGroup?: DeserializedType<T, 'Edm.String'> | null;
  psaIsFinal?: NoYes | null;
  lineDisc: DeserializedType<T, 'Edm.Decimal'>;
  multiLnDisc: DeserializedType<T, 'Edm.Decimal'>;
  purchaseLineLineNumber: DeserializedType<T, 'Edm.Int64'>;
  tax1099BoxDetail: DeserializedType<T, 'Edm.Int64'>;
  description?: DeserializedType<T, 'Edm.String'> | null;
  pdsCwReceiveNow: DeserializedType<T, 'Edm.Decimal'>;
  agreementLinePsn: DeserializedType<T, 'Edm.Int64'>;
  tax1099Fields: DeserializedType<T, 'Edm.Int64'>;
  addressRefTableId: DeserializedType<T, 'Edm.Int32'>;
  origCountryRegionId?: DeserializedType<T, 'Edm.String'> | null;
  lineType?: PurchInvoiceLineType | null;
  remainAfter: DeserializedType<T, 'Edm.Decimal'>;
  sysRecVersion: DeserializedType<T, 'Edm.Int32'>;
  psaRetainagePercent: DeserializedType<T, 'Edm.Decimal'>;
  orderAccount?: DeserializedType<T, 'Edm.String'> | null;
  purchPrice: DeserializedType<T, 'Edm.Decimal'>;
  countyOrigDest?: DeserializedType<T, 'Edm.String'> | null;
  origStateId?: DeserializedType<T, 'Edm.String'> | null;
  addressRefRecId: DeserializedType<T, 'Edm.Int64'>;
  remainBefore: DeserializedType<T, 'Edm.Decimal'>;
  lineAmount: DeserializedType<T, 'Edm.Decimal'>;
  psaReleaseAmount: DeserializedType<T, 'Edm.Decimal'>;
  pdsCwRemainAfter: DeserializedType<T, 'Edm.Decimal'>;
  tax1099State?: DeserializedType<T, 'Edm.String'> | null;
  pdsCwRemainBefore: DeserializedType<T, 'Edm.Decimal'>;
  requestStatus?: VendInvoiceRequestStatus | null;
  psaRetainageAmount: DeserializedType<T, 'Edm.Decimal'>;
  purchLineRecId: DeserializedType<T, 'Edm.Int64'>;
  taxGroup?: DeserializedType<T, 'Edm.String'> | null;
  parmId?: DeserializedType<T, 'Edm.String'> | null;
  taxWithholdItemGroupHeadingId: DeserializedType<T, 'Edm.Int64'>;
  psaRetainageBalance: DeserializedType<T, 'Edm.Decimal'>;
  tax1099StateAmount: DeserializedType<T, 'Edm.Decimal'>;
  intrastatCommodity: DeserializedType<T, 'Edm.Int64'>;
  sourceDocumentLine: DeserializedType<T, 'Edm.Int64'>;
  changedManually?: NoYes | null;
  lineNum: DeserializedType<T, 'Edm.Decimal'>;
  currencyCode?: DeserializedType<T, 'Edm.String'> | null;
  procurementCategory: DeserializedType<T, 'Edm.Int64'>;
  itemId?: DeserializedType<T, 'Edm.String'> | null;
  tax1099Amount: DeserializedType<T, 'Edm.Decimal'>;
  overrideSalesTax?: NoYes | null;
  remainAfterInvent: DeserializedType<T, 'Edm.Decimal'>;
  multiLnPercent: DeserializedType<T, 'Edm.Decimal'>;
  taxItemGroup?: DeserializedType<T, 'Edm.String'> | null;
  receiveNow: DeserializedType<T, 'Edm.Decimal'>;
  statProcId?: DeserializedType<T, 'Edm.String'> | null;
  remainBeforeInventPhysical: DeserializedType<T, 'Edm.Decimal'>;
  tableRefId?: DeserializedType<T, 'Edm.String'> | null;
  budgetReservationLinePsn: DeserializedType<T, 'Edm.Int64'>;
  transactionCode?: DeserializedType<T, 'Edm.String'> | null;
  inventNow: DeserializedType<T, 'Edm.Decimal'>;
  linePercent: DeserializedType<T, 'Edm.Decimal'>;
  invoiceLineNum: DeserializedType<T, 'Edm.Decimal'>;
  deliveryName?: DeserializedType<T, 'Edm.String'> | null;
  inventTransId?: DeserializedType<T, 'Edm.String'> | null;
  port?: DeserializedType<T, 'Edm.String'> | null;
}
