/*
 * Copyright (c) 2025 SAP SE or an SAP affiliate company. All rights reserved.
 *
 * This is a generated file powered by the SAP Cloud SDK for JavaScript.
 */
/**
 * This enum represents the enum type "{@link Timezone}".
 * The members represent values of EDM type Edm.Int32.
 */
export enum Timezone {
  /**
   * Original value: 24
   */
  GMTMINUS1200INTERNATIONALDATELINEWEST = 'GMTMINUS1200INTERNATIONALDATELINEWEST',
  /**
   * Original value: 99
   */
  GMTMINUS1100COORDINATEDUNIVERSALTIME = 'GMTMINUS1100COORDINATEDUNIVERSALTIME',
  /**
   * Original value: 65
   */
  GMTMINUS1100MIDWAYISLAND_SAMOA = 'GMTMINUS1100MIDWAYISLAND_SAMOA',
  /**
   * Original value: 39
   */
  GMTMINUS1000HAWAII = 'GMTMINUS1000HAWAII',
  /**
   * Original value: 2
   */
  GMTMINUS0900ALASKA = 'GMTMINUS0900ALASKA',
  /**
   * Original value: 58
   */
  GMTMINUS0800PACIFICTIME = 'GMTMINUS0800PACIFICTIME',
  /**
   * Original value: 59
   */
  GMTMINUS0800TIJUANA_BAJACALIFORNIA = 'GMTMINUS0800TIJUANA_BAJACALIFORNIA',
  /**
   * Original value: 75
   */
  GMTMINUS0700ARIZONA = 'GMTMINUS0700ARIZONA',
  /**
   * Original value: 47
   */
  GMTMINUS0700MOUNTAINTIME = 'GMTMINUS0700MOUNTAINTIME',
  /**
   * Original value: 48
   */
  GMTMINUS0700CHIHUAHUA_LAPAZ_MAZATLAN = 'GMTMINUS0700CHIHUAHUA_LAPAZ_MAZATLAN',
  /**
   * Original value: 15
   */
  GMTMINUS0600CENTRALAMERICA = 'GMTMINUS0600CENTRALAMERICA',
  /**
   * Original value: 21
   */
  GMTMINUS0600CENTRALTIME = 'GMTMINUS0600CENTRALTIME',
  /**
   * Original value: 22
   */
  GMTMINUS0600GUADALAJARA_MEXICOCITY = 'GMTMINUS0600GUADALAJARA_MEXICOCITY',
  /**
   * Original value: 11
   */
  GMTMINUS0600SASKATCHEWAN = 'GMTMINUS0600SASKATCHEWAN',
  /**
   * Original value: 63
   */
  GMTMINUS0500BOGOTA_LIMA_QUITO_RIOBRANCO = 'GMTMINUS0500BOGOTA_LIMA_QUITO_RIOBRANCO',
  /**
   * Original value: 29
   */
  GMTMINUS0500EASTERNTIME = 'GMTMINUS0500EASTERNTIME',
  /**
   * Original value: 74
   */
  GMTMINUS0500INDIANA = 'GMTMINUS0500INDIANA',
  /**
   * Original value: 255
   */
  GMTMINUS0500CHETUMAL = 'GMTMINUS0500CHETUMAL',
  /**
   * Original value: 95
   */
  GMTMINUS0400ASUNCION = 'GMTMINUS0400ASUNCION',
  /**
   * Original value: 6
   */
  GMTMINUS0400ATLANTICTIME = 'GMTMINUS0400ATLANTICTIME',
  /**
   * Original value: 64
   */
  GMTMINUS0400LAPAZ = 'GMTMINUS0400LAPAZ',
  /**
   * Original value: 17
   */
  GMTMINUS0400MANAUS = 'GMTMINUS0400MANAUS',
  /**
   * Original value: 57
   */
  GMTMINUS0300SANTIAGO = 'GMTMINUS0300SANTIAGO',
  /**
   * Original value: 85
   */
  GMTMINUS0430CARACAS = 'GMTMINUS0430CARACAS',
  /**
   * Original value: 54
   */
  GMTMINUS0330NEWFOUNDLAND = 'GMTMINUS0330NEWFOUNDLAND',
  /**
   * Original value: 87
   */
  GMTMINUS0300_SALVADOR = 'GMTMINUS0300_SALVADOR',
  /**
   * Original value: 28
   */
  GMTMINUS0300BRASILIA = 'GMTMINUS0300BRASILIA',
  /**
   * Original value: 86
   */
  GMTMINUS0300BUENOSAIRES = 'GMTMINUS0300BUENOSAIRES',
  /**
   * Original value: 62
   */
  GMTMINUS0300BUENOSAIRES_GEORGETOWN = 'GMTMINUS0300BUENOSAIRES_GEORGETOWN',
  /**
   * Original value: 36
   */
  GMTMINUS0300GREENLAND = 'GMTMINUS0300GREENLAND',
  /**
   * Original value: 83
   */
  GMTMINUS0300MONTEVIDEO = 'GMTMINUS0300MONTEVIDEO',
  /**
   * Original value: 45
   */
  GMTMINUS0200MIDATLANTIC = 'GMTMINUS0200MIDATLANTIC',
  /**
   * Original value: 10
   */
  GMTMINUS0100AZORES = 'GMTMINUS0100AZORES',
  /**
   * Original value: 12
   */
  GMTMINUS0100CAPEVERDIS = 'GMTMINUS0100CAPEVERDIS',
  /**
   * Original value: 93
   */
  GMT_CASABLANCA = 'GMT_CASABLANCA',
  /**
   * Original value: 37
   */
  GMT_CASABLANCA_MONTROVIA_REYKJAVIK = 'GMT_CASABLANCA_MONTROVIA_REYKJAVIK',
  /**
   * Original value: 89
   */
  GMT_COORDINATEDUNIVERSALTIME = 'GMT_COORDINATEDUNIVERSALTIME',
  /**
   * Original value: 35
   */
  GMT_DUBLIN_EDINBURGH_LISBON_LONDON = 'GMT_DUBLIN_EDINBURGH_LISBON_LONDON',
  /**
   * Original value: 90
   */
  GMT_PLUS0300KALININGRAD_MINSK = 'GMT_PLUS0300KALININGRAD_MINSK',
  /**
   * Original value: 79
   */
  GMTPLUS0100_AMSTERDAM_BERLIN_BERN_ROME = 'GMTPLUS0100_AMSTERDAM_BERLIN_BERN_ROME',
  /**
   * Original value: 18
   */
  GMTPLUS0100BELGRADE_BRATISLAVA_BUDAPEST = 'GMTPLUS0100BELGRADE_BRATISLAVA_BUDAPEST',
  /**
   * Original value: 60
   */
  GMTPLUS0100BRUSSELS_COPENHAGEN_MADRID = 'GMTPLUS0100BRUSSELS_COPENHAGEN_MADRID',
  /**
   * Original value: 19
   */
  GMTPLUS0100SARAJEVO_SKOPJE_WARSAW_ZAGREB = 'GMTPLUS0100SARAJEVO_SKOPJE_WARSAW_ZAGREB',
  /**
   * Original value: 101
   */
  GMTPLUS0100TRIPOLI = 'GMTPLUS0100TRIPOLI',
  /**
   * Original value: 78
   */
  GMTPLUS0100WESTCENTRALAFRICA = 'GMTPLUS0100WESTCENTRALAFRICA',
  /**
   * Original value: 96
   */
  GMTPLUS0200_DAMASCUS = 'GMTPLUS0200_DAMASCUS',
  /**
   * Original value: 43
   */
  GMTPLUS0200AMMAN = 'GMTPLUS0200AMMAN',
  /**
   * Original value: 38
   */
  GMTPLUS0200ATHENS_BUCHAREST_ISTANBUL = 'GMTPLUS0200ATHENS_BUCHAREST_ISTANBUL',
  /**
   * Original value: 46
   */
  GMTPLUS0200BEIRUT = 'GMTPLUS0200BEIRUT',
  /**
   * Original value: 27
   */
  GMTPLUS0200MINSK = 'GMTPLUS0200MINSK',
  /**
   * Original value: 30
   */
  GMTPLUS0200CAIRO = 'GMTPLUS0200CAIRO',
  /**
   * Original value: 68
   */
  GMTPLUS0200HARARE_PRETORIA = 'GMTPLUS0200HARARE_PRETORIA',
  /**
   * Original value: 33
   */
  GMTPLUS0200HELSINKI_KYIV_RIGA_VILNIUS = 'GMTPLUS0200HELSINKI_KYIV_RIGA_VILNIUS',
  /**
   * Original value: 98
   */
  GMTPLUS0300ISTANBUL = 'GMTPLUS0300ISTANBUL',
  /**
   * Original value: 42
   */
  GMTPLUS0200JERUSALEM = 'GMTPLUS0200JERUSALEM',
  /**
   * Original value: 51
   */
  GMTPLUS0200WINDHOEK = 'GMTPLUS0200WINDHOEK',
  /**
   * Original value: 5
   */
  GMTPLUS0300BAGHDAD = 'GMTPLUS0300BAGHDAD',
  /**
   * Original value: 3
   */
  GMTPLUS0300KUWAIT_RIYADH = 'GMTPLUS0300KUWAIT_RIYADH',
  /**
   * Original value: 61
   */
  GMTPLUS0300MOSCOW_STPETERSBURG_VOLGOGRAD = 'GMTPLUS0300MOSCOW_STPETERSBURG_VOLGOGRAD',
  /**
   * Original value: 25
   */
  GMTPLUS0300NAIROBI = 'GMTPLUS0300NAIROBI',
  /**
   * Original value: 34
   */
  GMTPLUS0300TBILISI = 'GMTPLUS0300TBILISI',
  /**
   * Original value: 41
   */
  GMTPLUS0330TEHRAN = 'GMTPLUS0330TEHRAN',
  /**
   * Original value: 4
   */
  GMTPLUS0400ABUDHABI_MUSCAT = 'GMTPLUS0400ABUDHABI_MUSCAT',
  /**
   * Original value: 9
   */
  GMTPLUS0400BAKU = 'GMTPLUS0400BAKU',
  /**
   * Original value: 104
   */
  GMTPLUS0400IZHEVSK_SAMARA = 'GMTPLUS0400IZHEVSK_SAMARA',
  /**
   * Original value: 84
   */
  GMTPLUS0400CAUCASUSSTANDARDTIME = 'GMTPLUS0400CAUCASUSSTANDARDTIME',
  /**
   * Original value: 92
   */
  GMTPLUS0400PORTLOUIS = 'GMTPLUS0400PORTLOUIS',
  /**
   * Original value: 13
   */
  GMTPLUS0400YEREVAN = 'GMTPLUS0400YEREVAN',
  /**
   * Original value: 1
   */
  GMTPLUS0430KABUL = 'GMTPLUS0430KABUL',
  /**
   * Original value: 31
   */
  GMTPLUS0500EKATERINBURG = 'GMTPLUS0500EKATERINBURG',
  /**
   * Original value: 94
   */
  GMTPLUS0500ISLAMABAD_KARACHI = 'GMTPLUS0500ISLAMABAD_KARACHI',
  /**
   * Original value: 255
   */
  GMTPLUS0500ISLAMABAD_KARACHI_TASHKENT = 'GMTPLUS0500ISLAMABAD_KARACHI_TASHKENT',
  /**
   * Original value: 40
   */
  GMTPLUS0530CHENNAI_KOLKATA_MUMBAI = 'GMTPLUS0530CHENNAI_KOLKATA_MUMBAI',
  /**
   * Original value: 69
   */
  GMTPLUS0530SRIJAYAWARDENEPURA = 'GMTPLUS0530SRIJAYAWARDENEPURA',
  /**
   * Original value: 52
   */
  GMTPLUS0545KATHMANDU = 'GMTPLUS0545KATHMANDU',
  /**
   * Original value: 50
   */
  GMTPLUS0600ALMATY_NOVOSIBIRSK = 'GMTPLUS0600ALMATY_NOVOSIBIRSK',
  /**
   * Original value: 16
   */
  GMTPLUS0600ASTANA_DHAKA = 'GMTPLUS0600ASTANA_DHAKA',
  /**
   * Original value: 88
   */
  GMTPLUS0600DHAKA = 'GMTPLUS0600DHAKA',
  /**
   * Original value: 91
   */
  GMTPLUS0600MAGADAN = 'GMTPLUS0600MAGADAN',
  /**
   * Original value: 49
   */
  GMTPLUS0630_YANGON = 'GMTPLUS0630_YANGON',
  /**
   * Original value: 66
   */
  GMTPLUS0700_BANGKOK_HANOI_JAKARTA = 'GMTPLUS0700_BANGKOK_HANOI_JAKARTA',
  /**
   * Original value: 56
   */
  GMTPLUS0700KRASNOYARSK = 'GMTPLUS0700KRASNOYARSK',
  /**
   * Original value: 97
   */
  GMTPLUS0800_ULAANBAATAR = 'GMTPLUS0800_ULAANBAATAR',
  /**
   * Original value: 23
   */
  GMTPLUS0800BEIJING_CHONGQING_HONGKONG = 'GMTPLUS0800BEIJING_CHONGQING_HONGKONG',
  /**
   * Original value: 55
   */
  GMTPLUS0800IRKUTSK_ULAANBATAAR = 'GMTPLUS0800IRKUTSK_ULAANBATAAR',
  /**
   * Original value: 67
   */
  GMTPLUS0800KUALALUMPUR_SINGAPORE = 'GMTPLUS0800KUALALUMPUR_SINGAPORE',
  /**
   * Original value: 77
   */
  GMTPLUS0800PERTH = 'GMTPLUS0800PERTH',
  /**
   * Original value: 70
   */
  GMTPLUS0800TAIPEI = 'GMTPLUS0800TAIPEI',
  /**
   * Original value: 72
   */
  GMTPLUS0900OSAKA_SAPPORO_TOKYO = 'GMTPLUS0900OSAKA_SAPPORO_TOKYO',
  /**
   * Original value: 44
   */
  GMTPLUS0900SEOUL = 'GMTPLUS0900SEOUL',
  /**
   * Original value: 82
   */
  GMTPLUS0900YAKUTSK = 'GMTPLUS0900YAKUTSK',
  /**
   * Original value: 14
   */
  GMTPLUS0930ADELAIDE = 'GMTPLUS0930ADELAIDE',
  /**
   * Original value: 7
   */
  GMTPLUS0930DARWIN = 'GMTPLUS0930DARWIN',
  /**
   * Original value: 26
   */
  GMTPLUS1000BRISBANE = 'GMTPLUS1000BRISBANE',
  /**
   * Original value: 8
   */
  GMTPLUS1000CANBERRA_MELBOURNE_SYDNEY = 'GMTPLUS1000CANBERRA_MELBOURNE_SYDNEY',
  /**
   * Original value: 81
   */
  GMTPLUS1000GUAM_PORTMORESBY = 'GMTPLUS1000GUAM_PORTMORESBY',
  /**
   * Original value: 71
   */
  GMTPLUS1000HOBART = 'GMTPLUS1000HOBART',
  /**
   * Original value: 76
   */
  GMTPLUS1000VLADIVOSTOK = 'GMTPLUS1000VLADIVOSTOK',
  /**
   * Original value: 102
   */
  GMTPLUS1100CHOKURDAKH = 'GMTPLUS1100CHOKURDAKH',
  /**
   * Original value: 20
   */
  GMTPLUS1100MAGADAN_SOLOMONIS = 'GMTPLUS1100MAGADAN_SOLOMONIS',
  /**
   * Original value: 103
   */
  GMTPLUS1200ANADYR_PETRO_KAMCHATSKY = 'GMTPLUS1200ANADYR_PETRO_KAMCHATSKY',
  /**
   * Original value: 53
   */
  GMTPLUS1200AUCKLAND_WELLINGTON = 'GMTPLUS1200AUCKLAND_WELLINGTON',
  /**
   * Original value: 100
   */
  GMTPLUS1200COORDINATEDUNIVERSALTIME = 'GMTPLUS1200COORDINATEDUNIVERSALTIME',
  /**
   * Original value: 32
   */
  GMTPLUS1200FIJI_KAMCHATKA_MARSHALLIS = 'GMTPLUS1200FIJI_KAMCHATKA_MARSHALLIS',
  /**
   * Original value: 73
   */
  GMTPLUS1300NUKU_ALOFA = 'GMTPLUS1300NUKU_ALOFA'
}
